### ISSUE TITLE
Cannot build with Qt 6.3.0 on macOS

### ISSUE THREAD

**Issue by agatti** [EKA2L1/EKA2L1#420]
**Describe the bug**
The source tree cannot build with Qt6 6.3.0 on macOS.  The cmake project doesn't set an appropriate target OS version (see error log below).

**To Reproduce**
1. Install Qt 6.3.0, via MacPorts, Homebrew, etc.
2. Build the code (I'm using the latest master: 02407e27b3cf21090d1806fb361afe44d1271efb)
3. See error.

**Expected behavior**
The Qt-related code should compile.

**Screenshots**

```
In file included from /Users/agatti/src/EKA2L1/src/emu/qt/src/aboutdialog.cpp:27:
In file included from /opt/homebrew/lib/QtCore.framework/Headers/QFile:1:
/opt/homebrew/lib/QtCore.framework/Headers/qfile.h:67:58: error: 'path' is unavailable: introduced in macOS 10.15
inline QString fromFilesystemPath(const std::filesystem::path &path)
                                                         ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk/usr/include/c++/v1/filesystem:909:24: note: 'path' has been explicitly marked unavailable here
class _LIBCPP_TYPE_VIS path {
```

**Your PC or smartphone specs**
- OS version: macOS 12.3
- The CPU you are using: m1
- The GPU you are using: Not related.

**Your emulator configuration**
- Not related.

**Log**
- Not related.

**Comment by yeatse** [comment]
Done on latest build
